name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: version
    attributes:
      label: gspy version
      description: What version of gspy are you using? (e.g. 0.1.0)
    validations:
      required: true
  - type: input
    id: go_version
    attributes:
      label: Go version
      description: What version of Go is the target binary using? (e.g. go1.21.5)
    validations:
      required: true
  - type: input
    id: kernel
    attributes:
      label: Kernel version
      description: Output of uname -r
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
    validations:
      required: true
